### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by AlessandroCavaglia** [aryklein/dualBootMouse#1]
File "./dualBootMouse.py", line 59, in <module>
    config.set('IdentityResolvingKey', 'Key', IRK)
NameError: name 'IRK' is not defined

the program crashes and gives this error

**Comment by aryklein** [comment]
Thanks @AlessandroCavaglia for submitting this issue. 
It seems that the Windows file you get with `psexec64.exe` changed over the time. Keep in mind that I made this script 2 years ago. Anyway, I will try to fix it to work with the latest format.

**Comment by AlessandroCavaglia** [comment]
Thank you

**Comment by aryklein** [comment]
@AlessandroCavaglia the issue was fixed in the commit: 664cda81155645b1b8b5cce0980a41632bd262e3
I tested it with my Windows 10 version 1909. Please let me know if it works for you.
Thanks

**Comment by aryklein** [comment]
Please read the new `README.rst` file because an extra argument is needed.
